### ISSUE TITLE
undefined method `broadcast' for ActiveSupport::Logger:Class in Rails 7.1.0.rc2

### ISSUE THREAD

**Issue by phil-6** [sidekiq/sidekiq#6063]
Ruby version: 3.2.2
Rails version: 7.1.0.rc2
Sidekiq / Pro / Enterprise version(s): Sidekiq - 7.1.4

Running as close to stock as possible. 

I suspect this is from the new public API for broadcasting logs introduced in Rails 7.1.0.rc1
https://github.com/rails/rails/releases/tag/v7.1.0.rc1

I understand this is a bug for an pre-release version of Rails, please close if inappropriate. 

backtrace
```
undefined method `broadcast' for ActiveSupport::Logger:Class
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:52:in `block (2 levels) in <class:Rails>'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq.rb:98:in `configure_server'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:47:in `block in <class:Rails>'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc2/lib/rails/initializable.rb:32:in `run'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc2/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc2/lib/rails/initializable.rb:60:in `run_initializers'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc2/lib/rails/application.rb:423:in `initialize!'
/home/phil/dev/ryalto/ryalto-v4/config/environment.rb:5:in `<top (required)>'
<internal:/home/phil/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/phil/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/cli.rb:303:in `boot_application'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/cli.rb:42:in `run'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sidekiq-7.1.4/bin/sidekiq:31:in `<top (required)>'
/home/phil/.rbenv/versions/3.2.2/bin/sidekiq:25:in `load'
/home/phil/.rbenv/versions/3.2.2/bin/sidekiq:25:in `<top (required)>'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/phil/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
/home/phil/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/home/phil/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```

**Comment by excid3** [comment]
Ran into this just now as well.

**Comment by phil-6** [comment]
I'm wondering this is fixed by https://github.com/sidekiq/sidekiq/pull/6060 but not released yet?

**Comment by excid3** [comment]
Looks like this is fixed in `main` but not released yet.

**Comment by excid3** [comment]
Meant to reply earlier, but the fix in main does the trick. 👍 

Maybe @mperham can get a new release out today.

**Comment by excid3** [comment]
LOL Thanks!

**Comment by thomasleese** [comment]
I think this issue is still present in the `6-x` branch. The following lines still rely on `ActiveSupport::Logger.broadcast` rather than `ActiveSupport::BroadcastLogger`.

https://github.com/sidekiq/sidekiq/blob/f67a7abccffc9337f144e7be96bb1ed4b0fee49a/lib/sidekiq/rails.rb#L45-L47

Is it possible to fix this for the 6.x releases, or I can raise a PR against the `6-x` branch if that's helpful.
